

server:
  port: 8085
spring:
  web:
    resources:
      add-mappings: false
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/titanium
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  mvc:
    consumes: application/json
    produces: application/json
    throw-exception-if-no-handler-found: true
  security:
    secret: "exemplo-aula-jwt"
    expiration_time: 240